"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

# Alias mode :- python setup.py py2app -A
# Production :- python setup.py py2app
# Cleanup :- rm -rf build dist
# Run :- open "dist/CryptoCoin Quotes.app"
# Through terminal : ./dist/CryptoCoin\ Quotes.app/Contents/MacOS/statusbarclient

from setuptools import setup
from statusbarclient import __version__

APP = ['statusbarclient.py']
APP_NAME = "CryptoCoin Quotes"
APP_VERSION = __version__
DATA_FILES = ['./icons']
OPTIONS = {
    'iconfile': '/Users/Sayan/Desktop/Projects/CryptoTicker/macosAssets/icon.icns',
    'argv_emulation': True,
    'plist': {
        'LSUIElement': True,
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "Get crypto coin quotes ASAP!",
        'CFBundleIdentifier': "com.sayangoswami.osx.cryptoquotes",
        'CFBundleVersion': APP_VERSION,
        'CFBundleShortVersionString': APP_VERSION,
        'NSHumanReadableCopyright': u"Copyright © 2017, Sayan Goswami, All Rights Reserved"
    },
    'packages': ['rumps', 'requests'],
}

setup(
    app=APP,
    name=APP_NAME,
    data_files=DATA_FILES,
    version=APP_VERSION,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
    install_requires=['rumps', 'requests'],
)
